### ISSUE TITLE
On Mobile

### ISSUE THREAD

**Issue by erossini** [slav123/SpryMap#5]
Hi there,
I have another issue. This script doesn't work on mobile devices. Do you work out something?
Thanks in advance

**Comment by xloong** [comment]
view [https://github.com/xloong/SpryMap](https://github.com/xloong/SpryMap)

**Comment by slav123** [comment]
Hi,


What am I looking at? Can you make a pull request? And give me some
context?


Slawomir Jasinski [swə'vɒmɪə jə'sɪnski]
